### ISSUE TITLE
plotting continuous data

### ISSUE THREAD

**Issue by Jules1989** [csn-le/wave_clus#117]
Hi,
I´m not very familiar with wave_clus, so I already have some difficulties with loading the trace. My recordings are 10 minutes long, but wave_clus is just plotting a length of one minute. Can I change it, so I can see and work with the whole trace?

Thank you!

**Comment by ferchaure** [comment]
Hi,
Try using a greater value for the parameter par.cont_plot_samples

**Comment by Jules1989** [comment]
Unfortunately , that doesn´t change anything. Isn´t it just changing the number of samples within one minute?

**Comment by ferchaure** [comment]
You are right. If you want to change the length of that plot can edit the 60 from [the line 234 of readInData](https://github.com/csn-le/wave_clus/blob/90db59172b57718582c1b9e8948119a0f09e60c8/Batch_files/readInData.m#L234).

Otherwise you can use the same filters using matlab, all that code is in [amp_detect.m](https://github.com/csn-le/wave_clus/blob/master/Batch_files/amp_detect.m)

**Comment by Jules1989** [comment]
So, did I get it right, that it´s just a plotting thing? All the detected spikes that are shown, are from the whole recording and not only within the plotted length? 

The first option already helped me to elongate the trace to 240s, but that´s the limit. 

Thanks a lot.

**Comment by ferchaure** [comment]
> So, did I get it right, that it´s just a plotting thing? All the detected spikes that are shown, are from the whole recording and not only within the plotted length?

Yes, and notice that this plot is using the detection filter

**Comment by Jules1989** [comment]
I see. Thank you so much for your help.
