### ISSUE TITLE
Is Wave_Clus suitable for performing spike sorting on in vivo electrophysiological signals recorded in urethane?

### ISSUE THREAD

**Issue by MartaB86** [csn-le/wave_clus#135]
Hi,
I just started to use Wave_Clus because I am interested in doing spike sorting on my data. In particular, my signals have been acquired in vivo using a probe inserted into the rat somatosensory cortex being anesthetized using urethane. The sampling frequency is 25 kHz.
I have two concerns. Firstly, I noticed that I always get a Cluster 0 containing a high number of 'not-assigned' spikes, even though those spikes have amplitude and shape highly similar to other spikes that, instead, got assigned to a specific cluster. In the following figure ('Ch_01'), I show you an examplel with a zoom on the electrophysiological trace. There are 4 spikes, two assigned to the red cluster (Cluster 2) and two assigned to the black cluster (Cluster 0). To me, it looks like they should belong to the same cluster so I wonder if this could be a matter of shape signal or of tuning of specific parameters (even if I already tried to play with SPC parameters such as min_clus). Do you have any suggestion about this point?
![Ch_01](https://user-images.githubusercontent.com/52494548/60591393-ad560480-9d9e-11e9-9b54-3929c624900e.jpg)
Secondly, there are several cases in which I have a sustained activity where no isolated spikes are present (see figure below - 'Ch_12') and the activity is bursting with spikes very close to each other. In this case, just one cluster is detected even though there are events characterized by very different shape and amplitude. Again I tried to play a little bit with parameters' value but without any improvement.
![Ch_12](https://user-images.githubusercontent.com/52494548/60592745-8e0ca680-9da1-11e9-9456-f26fa2e987f4.jpg)
Any help and/or suggestion would be very appreciated.
If you need other images or material to better document the issues, please ask.
Best,
Marta

**Comment by ferchaure** [comment]
Hi Marta,

Only to check, are you using a edited version of wave_clus? Check that is based in the last commit. I never accepted a pull request with that marks in the plot because the signal if filtered with a stronger filter for detection (and all the spikes look similar) and furthermore the signal is quite down sampled. 

The main limitation of waveclus are: it doesn't support probes with a high amount of electrodes and it does not handle overlapping spikes (this could be important in particular applications). 

About the issues you found :
Use a bit higher value of par.template_sdnum will reduce the cluater zero, but remember that could force noise into the classes. The high coulb be similar but the waveform not, if you want to visually check select from the cluster zero the spikes manually (this will create another cluster) and then se in the first subplot the differences between means. 

About the other case,  you could try using a bit higher value for par.maxtemp to check if the classes are separated in higher temperatures. Or reduce a bit min_clus (this could generate overclustering in other cases). If both methods can separate the classes, maybe you have to much noise to solve this sorting.

**Comment by MartaB86** [comment]
Hi Fernando,
Thanks for your fast response.
Regarding your question, I firstly downloaded wave_clus from your website and started using it as it is. Then, my supervisor asked me to be able to show which spikes correspond to which detected clusters so, when I found that pull request for adding colored marks on the electrophysiological trace, I just integrated the two modified scripts into your tool thinking that it would have not compromised the analysis. Indeed, I read your comments and answers to the request and it was not specified that it implied the use of a stronger filter for filtering signals.

Thank you for listing the main software limitations. I tried your suggestions for the two presented issues.
I changed par.template_sdnum (reaching a value of 20) but the number of spikes belonging to cluster 0 remained nearly the same (around 1800 spikes). Then I did as you suggested for visual check, i.e. I manually selected spikes from cluster 0 but I keep seeing groups of spikes having same amplitude and shape of spikes belonging to Cluster 2 for example.
Regarding the second issue, I modified both par.maxtemp and par.min_clus but the result did not change.
Do you think your tool could be easily (or, at least, pretty much) adapted to this type of signals? Or do you know other softwares that could work on them? Sorry for the naive question but I just started working with spike sorting methods.

Thanks again for your feedbacks.
Marta

**Comment by ferchaure** [comment]
For the cluster zero case: is quite odd, maybe using a smaller min_clus could help to find an extra class. can you showme an example? 

You could try MountainSort is a good spike sorter for a low number of channels. But is possible that the case where you couldn't separate neurons is just beacue the level of noise doesn't allow it.

**Comment by MartaB86** [comment]
Hi Fernando,
I decreased par.min_clus to 10, but still it did not work.
There could be a way for me to send you the mat files corresponding to these two electrodes? So you could have a look at them, if it is possible.
Otherwise, just tell me what it could be more useful for you to look at for better understanding.
Thank you very much in advance.
Best,
Marta

**Comment by ferchaure** [comment]
You can try to select the spc solution in the elbow temperature (that is usually just over-clustering but in your case could help ), that is the temperature where the gray zone start on the temperature plot in the GUI.  It is possible that the clusters 0 is: noise (the spike look can be from the filter and the alignment ) or sparse neurons (sometimes you can find them easily using a longer recording)
