### ISSUE TITLE
File format for multiple Channels 

### ISSUE THREAD

**Issue by LauPiVa** [csn-le/wave_clus#165]
Thank you very much for the feedback you give us. 
My records are with 60 channels and I want to sort with wave_clus, but it is not clear to me if I have to enter one file per channel or enter one file .mat per record with all channels as cells. 
I want to detect spikes from the raw signal, the sampling rate is 25kHz.

**Comment by ferchaure** [comment]
Hi LauPiVa

You should create a file per channel and then create a polytrode1.txt  with the names of that file, and finally call Get_spikes_pol(1). More info [here](https://github.com/csn-le/wave_clus/wiki/Polytrodes).

I would group the channels in neighbourhoods and create the polytrodes using just subgroups of channels. Otherwise, Wave_clus will handle quite poorly the 60 channels together.
