### ISSUE TITLE
about new_index

### ISSUE THREAD

**Issue by Jie369** [csn-le/wave_clus#168]
Hello, first of all, I'm sorry to bother you.Secondly, I would like to ask that the result of the time tag (index) generated by amp_detect is inconsistent with its own when processing simulation data.

**Comment by ferchaure** [comment]
It depends on the simulated data, but in principle, the source of a time inconsistency could be the definition of the time tag. For example, Wave_clus (and many others) defines the time tag of a spike as the sample where the peak of the spike is located. On the other hand in some simulations, the time tag is defined as the beginning of the spike waveform a few samples earlier than the peak.

**Comment by Jie369** [comment]
Hello, since the time tag is different, how to determine if the spike detected by the program is correct?Because I see that your team has an article that mentions Misses and False alarms.How are they compared?

**Comment by ferchaure** [comment]
The best way to do the alignment is:
1. Check for each neuron in the simulated file (after the filters you want to use) what is the difference between the simulated time tag and the peak in the signal.
2. In each case replace the time tag for the peak time tag.
3. Admit an error margin of 1 or 2 samples when you compare the time tags between the detection and the simulation.

**Comment by Jie369** [comment]
Where can I find the original time label in the program

**Comment by ferchaure** [comment]
What do you mean? Any algorithm will detect and give you the times of the peaks of the spikes (or some similar waveform dependent time). On the other hand, the simulations will have a time tag that you have to understand and work around to compare with the algorithms.

**Comment by Jie369** [comment]
First of all, I'm sorry if I offended you in any way.I don't doubt your experiment.I just have some questions.I don't know why the time tag of the simulated data is different from the time tag detected in the experiment.Is it because of alignment?Figure 1 is the time label that comes with the simulation data itself.Figure 2 presents a new time tag using your method.I wonder why they are different.I'm sorry to disturb you！
![yuan](https://user-images.githubusercontent.com/52561806/80276758-4afb3580-871d-11ea-8196-c9089fb9468d.png)
![test](https://user-images.githubusercontent.com/52561806/80276763-4e8ebc80-871d-11ea-8ed9-36c9b0fa7f5e.png)

**Comment by ferchaure** [comment]
I'm offended or anything like that. The issue is not about the software in particular, but about understanding the meaning of the time tag in the simulations.
For example, the spike 2 in the simulated data, was detected in the sample 3874 (first spike detected), remember that the detection is defined with the peak in the raw data. 
It looks like for that class the simulated waveform starts 22 samples before the peak, because the time tag of the simulation is 3852. 

In my awful drew spike, the red triangle is the time tag of the simulation and the blue triangle is the detection time, there the source of the time lag:
![Drawing](https://user-images.githubusercontent.com/5598671/80286940-d87e5b80-8704-11ea-8e17-f9228efa993f.png)

**Comment by Jie369** [comment]
Thank you very much!Sorry to disturb you.
