### ISSUE TITLE
is the manual button under the pc/waveform panel supposed to let me clean up waveforms in pc space?

### ISSUE THREAD

**Issue by LongLabGit** [csn-le/wave_clus#199]
![image](https://user-images.githubusercontent.com/29983043/133320168-9c3c14ad-248c-4b61-b82d-de30669adbd2.png)

i'd like to manually cut out the small cluster above the main one to see what the waveforms look like. i've never been able to manually do that when i click "manual"--is this supposed to be an option?

**Comment by ferchaure** [comment]
You are right,  the manual button is just for the "spikes shapes" the philosophy of wave_clus is centered on using the temperature map instead of the features and the manual curation is manly for fixing issues for the force step. 
It possible to add that code in the function manual_clus_button_Callback in wave_clus.m and checking the status of the Spike feature check box. But selecting spikes in a 2 dimensional feature space is not recommended.
