### ISSUE TITLE
The way to discriminate (reject) pseudo (false) spike?

### ISSUE THREAD

**Issue by MBLH** [csn-le/wave_clus#22]
Hi, I am not sure if I can ask this type of question here though, I will try anyway.
 Recently I am wondering which cluster to exclude from the further analysis.

For example in this case, I will take cluster 1, but I will reject cluster 2 and 3
because their shape don't look like spikes. Do you agree with my decision?
![ideal](https://cloud.githubusercontent.com/assets/16915193/20095008/04f8c374-a5e7-11e6-8bb7-8f96b6d2c309.jpg)

In another case, I will take cluster 1.
Then maybe I will reject cluster 2 because the spike shape on the 3rd channels doesn't have a negative peak, and the distribution of the magnitude of spike looks similar to that of cluster 1,
and cluster 2 has much fewer number of spikes... cluster 2 might be a part of cluster 1 population?
Further, I wonder if I should reject cluster 3 because the distribution of ISI has 2 peaks
and its spike shape doesn't look like a real spike??
![wave_clus](https://cloud.githubusercontent.com/assets/16915193/20095492/09b31b42-a5e9-11e6-9011-26fb7d1cd84b.jpg)

Next, this is the 3rd case. I will take cluster 2 especially because the second channel shows clear spike shape, but I will reject cluster 3 because its wave form seems like noise.
But the problem is cluster one. In channel 3, there is a big "spike?" but
ISI distribution looks zigzag. So should I reject it too?
![zigzag](https://cloud.githubusercontent.com/assets/16915193/20095743/1a8dfc88-a5ea-11e6-9aa6-62876272a992.jpg)

**Comment by ferchaure** [comment]
I'm not an expert in tetrode signals... but I will try to help

case 1: Do you check using only a negative threshold? Using both types donet help in you case. Worst case scenario, you can make two time, one with each type of threshold. Why don't you search for cluster in another temperatures? maybe the ugly clusters are better at other temperatures.

case 2: But... cluster 2 could be a neuron... maybe is't clear in all the electrodes but you shouldn't reject them because one electrode is far away of the neuron. 
The ISI and the spikes of cluster 3 are quite odd... maybe noise. You can try to find the pure noise cluster with manual or choosing another temperature. If you make a cluster with all that noise, it won't bother any more.

case 3: Again, the threshold aren't helping. Maybe, if you change par.stdmax and remove the noise, the plots will be more easy to understand.

**Comment by seble2016** [comment]
Hi Ferchaure,
I'm leaving my comment here as my question follows this thread already. 
Could you explain to me how one decides on temperatures? Is it arbitrary?

**Comment by ferchaure** [comment]
A few  rules of thumb about temperature selection: 
-  If you see a big increase in the size of the clusters when you increase the temperature, check the temperature after the increase. Because new clusters appeared and that could be neurons. 
-  Check the lower temperature for clusters with more than a few dozens of spikes. Noise or sparse neurons with a characterised waveform can be there.
-Remember that each temperature is a possible clustering of the data. If you found a nice cluster fix it always before change the temperature. 
-Sometimes you will find clusters in different temperatures with waveform too similar, merge them if you think that the difference is to close to the noise in the signal.
