### ISSUE TITLE
Reproducibility of results

### ISSUE THREAD

**Issue by maegin** [csn-le/wave_clus#35]
Hello and thanks a lot for this software!

I was wondering if there is a way to make the results from Wave_clus reproducible, in the sense that, when the program runs on the same file, with the same parameters, the two times_* output files are identical.

I tried to fix  par.randomseed to a number(not zero of course) and also rng before calling the program, still the results after clustering are slightly different. As far as I understand the only randomness should be in the clustering algorithm and perhaps setting par.randomseed doesn't work because the program uses an external .exe file?

Any possible solution to this?
Thanks in advance.

**Comment by ferchaure** [comment]
Hi, 
To be honest, I never tried to do this. But I can give you some tips:

- If  you are using Do_clustering,  set the argument 'parallel' as false. Maybe the problem is within the parfor and the random seed setting.
- There is more randomness (a randperm) inside Do_clustering.m and wave_clus.m for choose/order the spikes before the SPC. 
- par.randomseed should be an integer.

**Comment by maegin** [comment]
Hi,
Thanks for the reply.

So it seems the problem is indeed between the parfor and the random seed setting. 
Disabling the parallel option for now works. I will try if it is possible to use RandStream function from matlab for parallel computation.
