### ISSUE TITLE
Files load as read only for plotting

### ISSUE THREAD

**Issue by NeuroCLaw** [csn-le/wave_clus#38]
Hi, 
I am recording data using a BlackRock system then converting single channel files using parse_data_NSx.m. Sometimes this works and allows me to open the files in wave_clus. However I have now started getting an error which comes up as 'Segment read only for plotting' which means the data I open can't be edited. Each time I open a file using load in wave_clus, no matter how I set and save the parameters it opens the same way and can't be changed. Once this happens any data file opens in the same way.
Thanks in advance!

**Comment by ferchaure** [comment]
Hi, 
Probably it's not clear in the documentation... If you want to change the parameters used for the clustering, you have to remove the "times_" file (or change its name) and make a new one (after change the parameters). 
The 'Segment read only for plotting'  its there because wave_clus is loading the raw data in the .NC5 file only for the signal plot in the top panel.

**Comment by Catherine100** [comment]
Hello!
I think this could be my problem. Only the top panel changes. I can't find a "times_" file.
Thanks in advance!

**Comment by ferchaure** [comment]
If you don't want to see this warning, set `par.cont_segment = false `in the set_parameters file.
