### ISSUE TITLE
troubles importing spikes and index

### ISSUE THREAD

**Issue by ayanmandal18** [csn-le/wave_clus#44]
Hello, we would like to import into wave_clus the waveforms of our already detected spikes. Each waveform has a length of 3200 microseconds, so the file I load to wave_clus has a matrix named spikes with N by 32 dimensions (where N is number of waveforms for a single electrode). The file also includes index as a vector with the timestamps for each spike and sr as our sampling rate (10000 Hz). When I run it, I get this error message. My colleague is also getting an error message while using the spikes file in the sample data.

![wave_clus_error](https://user-images.githubusercontent.com/30474559/28635321-2cd94114-7208-11e7-8218-84065c908b54.png)

**Comment by ferchaure** [comment]
Hi, you have to change the parameters: w_pre and w_post.
The defaults are:

> par.w_pre = 20;       
> par.w_post = 44; 

For that reason the waveform try to have 64 samples and you only has 32. Remember to disable the interpolation if you set that parameters for a waveform of 32 samples, otherwise  you will get an error because extra samples are needed to remove the border effect of the interpolation.
