### ISSUE TITLE
SPC processing of detected polytrode spikes

### ISSUE THREAD

**Issue by bmi-lsym** [csn-le/wave_clus#52]
Hi,
Thank you for your great work!
I was wondering if there is a possibility to cluster **detected** spike waveforms from the tetrodes using SPC algorithm? I have been reading here on how to deal with polytrode's raw data using Get_spikes_poly, which however involves detection procedure by wave_clus. But my experiment requires separate detection. Is there a shortcut of how to proceed directly to SPC with the polytrode spike waveforms? Currently it works for me using one channel at a time (providing a .mat with 2D spike array and 1D timestamps array as described in the manual), but would really like to be able to do it for four channels.  
Thank you in advance!

**Comment by ferchaure** [comment]
Hi, after a detection Wave_clus concatenate the signal in each channel to make a "tetrode spike" of length = number of channels x  length of a spike.
If you make a file called _filename_\_spikes.mat with at least the variables _index_ and _spikes_(with the "tetrode spikes"), you could continue the sorting

**Comment by bmi-lsym** [comment]
Thanks, it works now! 
In fact, I tried it already before like that, but was not sure it is a good way to sort multitrode spikes.

And there was a technical problem: it would not load the concatenated cutouts with the number of sampling points more that "usual" 64 unless the detection parameters "par.w_pre" and "par.w_post" were adjusted to sum up to the required number of samples. (This trick I found in the previous recent answered issues.)

**Comment by docpaco78** [comment]
Thanks for this great work! I've started playing around with it and have a question related to the organization of the concatenated matrix referred to above. should it be:

spike1 ch1t0, ch1t1, ... ch1tend
spike1 ch2t0, ch2t1, ... ch2tend
spike1 ch3t0, ch3t1, ... ch3tend
spike1 ch4t0, ch4t1, ... ch4tend
spike2 ch1t0, ch1t1, ... ch1tend
spike2 ch2t0, ch2t1, ... ch2tend
spike2 ch3t0, ch3t1, ... ch3tend
spike2 ch4t0, ch4t1, ... ch4tend

or

spike1 ch1t0, ch1t1, ... ch1tend
spike2 ch1t0, ch1t1, ... ch1tend
spike1 ch2t0, ch2t1, ... ch2tend
spike2 ch2t0, ch2t1, ... ch2tend
spike1 ch3t0, ch3t1, ... ch3tend
spike2 ch3t0, ch3t1, ... ch3tend
spike1 ch4t0, ch4t1, ... ch4tend
spike2 ch4t0, ch4t1, ... ch4tend

or 

should it be a 3d matrix with each channel in the third dimension?

Hope that makes sense. Thanks in advance!

**Comment by ferchaure** [comment]
Hi,
I assume: ch1t0 = sample 0 [the first one] in channel 1 
The structure of that matrix is:
spike1: ch1t0, ch1t1, ... ch1tend, ch2t0, ch2t1, ... ch2tend,ch3t0, ch3t1, ... ch3tend, ch4t0, ch4t1, ... ch4tend
spike2: ch1t0, ch1t1, ... ch1tend, ch2t0, ch2t1, ... ch2tend,ch3t0, ch3t1, ... ch3tend, ch4t0, ch4t1, ... ch4tend
 etc

**Comment by docpaco78** [comment]
Thanks! I'll give it a try.

**Comment by docpaco78** [comment]
So, I just ran it and I get this error:

Unable to perform assignment because the size of the
left side is 19386-by-12 and the size of the right
side is 19386-by-10.

Error in spike_alignment (line 30)
    spikes1(:,1:align_window+2) =
    -spikes(:,align_window:-1:1);

Error in wave_clus>load_data_button_Callback (line
213)
            [spikes] =
            spike_alignment(spikes,handles.par);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:});
 
Error using cluster_tetrode_jt4 (line 144)
Error while evaluating UIControl Callback.

The spikes matrix is 19386 x 124 (31 ms sample on each channel). I'm using these parameters for alignment: 

par.w_pre = 10;                      % number of pre-event data points stored (default 20)                                                  
par.w_post = 15;                     % number of post-event data points stored (default 44))                                                
par.alignment_window = 10;           % number of points around the sample expected to be the

It does not throw this error if I have a matrix that is 77,544 x 31, whether the channels are interleaved or concatenated. Do I need to change the alignment parameters?

Thanks again!

**Comment by ferchaure** [comment]
Sorry for not tell you that:
-You need 2 extra samples in each border of each spike per channel because you will interpolate later
- Or yo can change the parameters and use par.interpolation = 'n'; 
I would recommend the first option sometimes the spikes are misaligned a fraction of a sample and that could affect the results.

**Comment by docpaco78** [comment]
So, I tried adding columns of zeros between channels and got the same error. I also tried turning off interpolation and still get the same error. Any thoughts?

**Comment by ferchaure** [comment]
Check that in each channel you have par.w_pre +par.w_post +par.alignment_window +2 samples per spike.

Have the spikes the peak in the sample 10? if that is the case, you can set par.alignment_window = 0 and par.interpolation = 'n';

**Comment by docpaco78** [comment]
I tried changing par.w_pre + par.w_post + par.alignment_window + 2 to equal the length of the spike, but still got the error. 

I changed lines 30-31 of spike_alignment.m from:
    spikes1(:,1:align_window+2) = -spikes(:,align_window:-1:1);
    spikes1(:,1+align_window:(2*align_window+ls)) = spikes(1:align_window+ls);

to:
    spikes1(:,1:align_window+2) = -spikes(:,align_window**+2**:-1:1);
    spikes1(:,1+align_window:(2*align_window+ls)) = spikes(**:**,1:align_window+ls);

which allowed the code to run, but generated only one cluster containing all the spikes. Any ideas on why it doesn't find any clusters with this method?

**Comment by ferchaure** [comment]
Are the spikes align to the sample  par.w_pre? are the sign of the peaks as par.detection?
I don´´t thing that correction is right. Did you try making the spikes one sample less? 

The spikes are quite short, 25 samples probably is not enough to discriminate the clusters.
