### ISSUE TITLE
Loading the data and interpreting the spike timings.

### ISSUE THREAD

**Issue by Ajoshis** [csn-le/wave_clus#79]
Hello

I have a raw dataset of 1x3257791 values saved as data.mat file.

When I try to load this file, it gives me the message as Wave_clus didn't find a sampling rate in file. It will use the set in set_parameters.m. However, it process the data and shows me clusters

Afterwards, when I try to save clusters, it gives me the following error messages-

Error using copyfile
Cannot write to destination: C:\Users\P1007\Desktop\data_data.dg_01.lab.  Use the 'f' option to override.

Error in wave_clus>save_clusters_button_Callback (line 549)
    copyfile([handles.par.fnamespc '.dg_01.lab'], [handles.par.fnamesave '.dg_01.lab']);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating uicontrol Callback

But saves the time_data file, when I open the 2nd column of  Cluster class it shows the spike times only upto the value of 1.0858e+05 which is less than the length of the raw data file (data.mat).

Moreover, when I compare the raw data signal with spike times they appears to be different.
I would be grateful if you could help me on this.

Regards,
Alok.

**Comment by ferchaure** [comment]
Hi Alok,

> When I try to load this file, it gives me the message as Wave_clus didn't find a sampling rate in file.

That is normal, is better if you have a variable **sr** in the file be to sure that you are using the right value. The message is only to let you know that is using the sampling rate in the set parameters.


> Error using copyfile
> Cannot write to destination: C:\Users\P1007\Desktop\data_data.dg_01.lab. Use the 'f' option to override.

That error is because that folder is read-only, you can try to move the data to a new folder, or edit that line in wave_clu (and the line below) adding the 'f' parameter to copyfile.

> But saves the time_data file, when I open the 2nd column of Cluster class it shows the spike times only upto the value of 1.0858e+05 which is less than the length of the raw data file (data.mat).

It could be the an error in the sampling rate or that you don't have spikes an the end of the file (or maybe a big artefact that corrupted the threshold)

> Moreover, when I compare the raw data signal with spike times they appears to be different.

That sounds like an issue in the set of the sampling rate.
