### ISSUE TITLE
How to  make the automatic clustering more 'rigorous'?

### ISSUE THREAD

**Issue by perczelgy** [csn-le/wave_clus#89]
Hi Fernando,

I am currently using Wave_clus 3.0 with par.foce_auto = false. However, though the results are better, it seems to me that the clusters are still too noisy. Is it possible to change some parameters to get the clustering more 'rigorous'?

Thank you: György

**Comment by ferchaure** [comment]
Hi György,
Check that the number of spikes is smaller that par.max_spk, otherwise the force methods will be use.  On the other hand, you can use force with a small value of par.template_sdnum.
If you tried all that, a smaller value of par.min_clus (~10) can be used, but it's possible that this will generate overclustering.
