### ISSUE TITLE
Crashing, Bug, Suggestion

### ISSUE THREAD

**Issue by aboharbf** [csn-le/wave_clus#97]
Crash:
The values denoted 'Default' in paratheses next to the arguments in the text box which appears when you hit "Set Parameters" aren't the same as those which populate the lines when you hit the "Default" button at the bottom of the box. Tuning the minimum cluster number and max cluster number to those values leads to the following crash:
"Reference to non-existent field 'fix14'.

Error in plot_spikes (line 112)
		eval(['fixx = par.fix' num2str(i) ';']);

Error in wave_clus>load_data_button_Callback (line 405)
plot_spikes(handles); %This function edits userdata

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating UIControl Callback."

Bug (sort of):
the latest version of the readNSx file from the NPMK Git Repo does not access any arguments with the word "parse". removing that argument fixes the issue.

Suggestions:
- Can a text box be introduced for changing the temperature? It is odd that we have to change cluster size with every click.
- There should be a crash message added somewhere on the GUI. If you're using it full screen you aren't aware its crashed unless it is taking unusually long.
- For those of us processing many files in the same dir, can the NSX# files produced have their original file name at the beginning? ([OriginalName]_times_NSX1.mat])
- Outside of the first run of the data, it doesn't seem to be possible to do the variable temperature cluster assignment (because when you click, only one temperature is available).
- Additional documentation explaining what curves in the temp graph would be useful. in particular I am confused with how to meaningfully interact/assess the 'x' of previous analyzed clusters.

**Comment by ferchaure** [comment]
> Crash:
The values denoted 'Default' in paratheses next to the arguments in the text box which appears when you hit "Set Parameters" aren't the same as those which populate the lines when you hit the "Default" button at the bottom of the box. Tuning the minimum cluster number and max cluster number to those values leads to the following crash:

You are totally right, we will change the values inside the parameters and the related crash in the next commit. The default values are those which populate the lines.

> Bug (sort of):
the latest version of the readNSx file from the NPMK Git Repo does not access any arguments with the word "parse". removing that argument fixes the issue.

Sorry I didn't follow that. I don't see a 'parse' argument in our function.

> Can a text box be introduced for changing the temperature? It is odd that we have to change cluster size with every click.

The exploration of the temperature map is qualitative and related to the lines, specific value should be so helpful, for that reason we didn't add another text box.

> There should be a crash message added somewhere on the GUI. If you're using it full screen you aren't aware its crashed unless it is taking unusually long.

To be honest, I don't know how to do something like that now, but its's a good idea.

> For those of us processing many files in the same dir, can the NSX# files produced have their original file name at the beginning? ([OriginalName]_times_NSX1.mat])

I don't thinks so. Wave_clus uses the "times_" at the beginning of the name to know how to open the file, and a lot of people use the default names of the ns5 files, that are quite long and could make difficult to check visually the files in the folder. A quick fix in your case, may be edit the line 52 in the parse_data_NSx and add the filename (without the path and extension) after the 'NSX'.

> Outside  of the first run of the data, it doesn't seem to be possible to do the variable temperature cluster assignment (because when you click, only one temperature is available).

You can fix (with the fix checkbox) the clusters you like, and they will continue if you change 1 time the temperature.

> Additional documentation explaining what curves in the temp graph would be useful. in particular I am confused with how to meaningfully interact/assess the 'x' of previous analyzed clusters.

They tell you that the automatic sorting didn't select those clusters because they spikes are in a selected clusters at high temperature. We are working on the improvement of the documentation.

**Comment by aboharbf** [comment]
Re: Blackrock - Sorry, misremembered the argument. I meant 'noread'. This argument is no longer needed.

Re: The Error - I can't quite find what function is called by the button, but you nesting this function in a try-catch loop could be a simple solution.

Re: Names - That's a good idea, I will try this instead.

I look forward to more documentation. This seems like a fantastic tool and I really hope to use it correctly. Thanks alot!
